In [1]:
import lsst.daf.persistence as dafPersist
import lsst.afw.table as afwTable
import lsst.afw.geom as afwGeom
import lsst.afw.image as afwImage
import numpy as np

visit = 11700
tract = 0
ccd = 12
filter = 'HSC-G'

# butler = dafPersist.Butler("/sps/lsst/dev/lsstprod/hsc/SSP_UDEEP_COSMOS/output/rerun/_parent/rerun")
butler = dafPersist.Butler("/sps/lsst/dev/lsstprod/hsc/SSP_UDEEP_COSMOS/output")
dataid = {'visit':visit, 'filter':filter, 'ccd':ccd}
dataidNew = {'visit':visit, 'filter':filter, 'ccd':ccd, 'tract':tract}

mdRef = butler.get("calexp_md", dataid, immediate=True)
oldWcs = afwImage.makeWcs(mdRef)
newWcs = butler.get('wcs', dataidNew, immediate=True).getWcs()

In [2]:
point = afwGeom.Point2D(100., 200.)

newCoord = newWcs.pixelToSky(point)
pointCheck = newWcs.skyToPixel(newCoord)

print("Verif new wcs - Point", point, "should be equal to ", pointCheck)
print(newCoord)

oldCoord = oldWcs.pixelToSky(point)
pointCheck = oldWcs.skyToPixel(oldCoord)

print("Verif old wcs - Point", point, "should be equal to ", pointCheck)
print(oldCoord)

Verif new wcs - Point (100, 200) should be equal to  (100, 200)
Fk5Coord(150.2235455, 1.6440167, 2000.00)
Verif old wcs - Point (100, 200) should be equal to  (100, 200)
Fk5Coord(150.2235362, 1.6440454, 2000.00)


In [3]:
dist = newCoord.angularSeparation(oldCoord).asArcseconds()*1000.
print(dist)

108.54406217587528


In [4]:
print(oldWcs.getCDMatrix())
print(newWcs.getCDMatrix())

[[  1.28504662e-07   4.62456701e-05]
 [  4.51033779e-05   3.14187300e-07]]
[[  1.57402813e-07   4.62418698e-05]
 [  4.51070316e-05   3.21864354e-07]]


In [5]:
print(oldWcs.getSipA())

[[  0.00000000e+00   0.00000000e+00   1.24484523e-06  -9.10189665e-14]
 [  0.00000000e+00  -4.74338600e-07  -1.44618443e-10   0.00000000e+00]
 [  4.01900663e-06  -8.12280021e-11   0.00000000e+00   0.00000000e+00]
 [ -3.04974624e-10   0.00000000e+00   0.00000000e+00   0.00000000e+00]]


In [6]:
print(newWcs.getSipA())

[[  1.08919425e+02   1.81621554e-02   1.85376790e-06   4.61798121e-12
   -5.35011794e-20  -1.97813714e-24   1.44715603e-29   2.75885685e-34
   -8.62595151e-40  -1.21730933e-44]
 [ -4.14039502e-02  -1.91795836e-06  -1.42443992e-10   5.20200440e-19
   -1.11167993e-24  -7.28294396e-29  -1.12116783e-34   3.38334774e-39
    1.38868384e-44   0.00000000e+00]
 [  5.51903588e-06   1.33134941e-11  -6.22836353e-19  -6.98825027e-24
    1.36247906e-28   1.70634443e-33  -9.09405073e-39  -1.08202245e-43
    0.00000000e+00   0.00000000e+00]
 [ -1.38320279e-10   7.92801566e-19   3.41495049e-24  -2.38185873e-28
   -1.32303155e-33   1.76276056e-38   1.20375990e-43   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [ -6.53180062e-19  -3.94214449e-24   2.53737489e-28   2.50552123e-33
   -2.45162533e-38  -2.64169266e-43   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  4.12213588e-24  -1.63011940e-28  -2.11911990e-33   2.51593339e-38
    2.60371689e-43   0.00000000e+00   0.00000

In [7]:
import lsst.daf.persistence as dafPersist
import lsst.afw.table as afwTable
import lsst.afw.geom as afwGeom
import lsst.afw.image as afwImage
import numpy as np

visit = 11700
tract = 0
filter = 'HSC-G'

# butler = dafPersist.Butler("/sps/lsst/dev/lsstprod/hsc/SSP_UDEEP_COSMOS/output/rerun/_parent/rerun")
butler = dafPersist.Butler("/sps/lsst/dev/lsstprod/hsc/SSP_UDEEP_COSMOS/output")

for ccd in range(104) :
    if ccd == 9 :
        continue
    
    dataid = {'visit':visit, 'filter':filter, 'ccd':ccd}
    dataidNew = {'visit':visit, 'filter':filter, 'ccd':ccd, 'tract':tract}

    mdRef = butler.get("calexp_md", dataid, immediate=True)
    oldWcs = afwImage.makeWcs(mdRef)
    newWcs = butler.get('wcs', dataidNew, immediate=True).getWcs()
    
    point = afwGeom.Point2D(2000., 2000.)

    newCoord = newWcs.pixelToSky(point)
    oldCoord = oldWcs.pixelToSky(point)
    dist = newCoord.angularSeparation(oldCoord).asArcseconds()*1000.
    dRa = (newCoord.getRa()-oldCoord.getRa()).asArcseconds()*1000.
    dDec = (newCoord.getDec()-oldCoord.getDec()).asArcseconds()*1000.

    print(dist, dRa, dDec)

16.441879268360683 16.42530994193434 0.8604849802463957
34.48097203081525 -21.6002350393419 -26.883164389676697
26.571625907323977 25.5626633611724 -7.2851728788956756
4.852756420603465 -3.961714025226803 2.8045414238797184
35.08293740628637 10.722824041113036 33.4055089765751
12.135073901401517 12.070329378386536 1.2984965433454052
22.592248529596187 8.078355851075763 -21.099832988695532
16.625897152924903 16.546854131731113 1.686640836121001
45.1638747250676 -35.72716934252451 -27.647532976041287
59.536097404629196 -8.099291941322027 58.98312146652037
44.96236830462992 -44.92046726318769 -2.368619795787595
56.35856940075387 52.164525047548395 -21.392316399951635
4.183479203967283 0.30001300074929504 4.172717637269244
28.417924846423723 -24.68484532201766 -14.099408052031851
20.971074146306208 -20.977740296818254 -0.352266388157572
39.189927290043 26.140531511960493 29.20883743851083
35.98002056941893 12.033354040948238 -33.91008388196529
32.58392953210332 21.88905241636802 -24.145859