In [10]:
%matplotlib inline
import lsst.daf.persistence as dafPersist
import lsst.afw.table as afwTable
import lsst.afw.geom as afwGeom
import lsst.afw.coord as afwCoord
import lsst.afw.image as afwImage
import lsst.geom as geom
import numpy as np
import matplotlib
import matplotlib.pylab as plt

from lsst.meas.algorithms import LoadIndexedReferenceObjectsTask

#setup butler - Replace path name by something suitable for you
butler = dafPersist.Butler("/pbs/throng/lsst/users/boutigny/clusters/MACSJ2243.3-0935/input")
#butler = dafPersist.Butler("/pbs/throng/lsst/users/boutigny/test")

refConfig = LoadIndexedReferenceObjectsTask.ConfigClass()
#refConfig.ref_dataset_name = 'pan-starrs'
refConfig.ref_dataset_name = 'gaia'
refTask = LoadIndexedReferenceObjectsTask(butler, config=refConfig)

#filt = 'g'                  # For pan-starrs
filt = 'phot_g_mean'         # For Gaia
flux = filt + '_flux'

center = geom.SpherePoint(5.94811*geom.radians, -0.163415*geom.radians)
print(center)
radius = 0.010
skyCircle = refTask.loadSkyCircle(center,
                                        geom.Angle(radius, geom.radians), filt)

refCat = skyCircle.refCat.copy(deep=True).asAstropy()

(340.801599, -9.362990)


In [16]:
md = refTask.getMetadataCircle(center,geom.Angle(radius, geom.radians), filt)

In [20]:
refTask.indexer.getShardIds(center,geom.Angle(radius, geom.radians))

(array([192197, 192201, 192202, 192203, 192204, 192205, 192207, 192245,
        192250, 192252]),
 <generator object HtmIndexer.getShardIds.<locals>.<genexpr> at 0x7efeb474cc50>)

In [2]:
refCat

<Table length=3966>
         id              coord_ra      ... phot_variable_flag
                           rad         ...                   
       int64             float64       ...       str52       
------------------- ------------------ ... ------------------
2608663286191100544  5.952529231444764 ...      NOT_AVAILABLE
2608551479602134144  5.954488657559802 ...      NOT_AVAILABLE
2608546158138065664  5.957431928940604 ...      NOT_AVAILABLE
2608645316047756544  5.955561369932886 ...      NOT_AVAILABLE
2608644186471667072  5.956259511556312 ...      NOT_AVAILABLE
2608641433397277952  5.957639893597756 ...      NOT_AVAILABLE
2608545196065391232  5.956593446809088 ...      NOT_AVAILABLE
2608550173932069248    5.9556313682819 ...      NOT_AVAILABLE
2608549967773638784  5.954954806960037 ...      NOT_AVAILABLE
                ...                ... ...                ...
2609337733495905152  5.947777863728409 ...      NOT_AVAILABLE
2609338558129627136 5.9472451451173045 ...      NOT_AVAILABLE
2609337458617997952  5.947900112120017 ...      NOT_AVAILABLE
2609337664776428288  5.947723246984718 ...      NOT_AVAILABLE
2609337394193160448  5.948201257468248 ...      NOT_AVAILABLE
2609338699863218944   5.94779492844622 ...      NOT_AVAILABLE
2609338665503480704  5.947572367325805 ...      NOT_AVAILABLE
2609431746034813440  5.948322914722374 ...      NOT_AVAILABLE
2609432497654087680  5.948204557868488 ...      NOT_AVAILABLE
2609337870934859008  5.947988156396179 ...      NOT_AVAILABLE

In [11]:
dataid = {'visit':1022181, 'filter':'r', 'ccd':10}
raw = butler.get('raw', dataid)
wcsRaw = raw.getWcs()
centerPixel = afwGeom.Point2D(2000., 2000.)
centerCoord = wcsRaw.pixelToSky(centerPixel)

/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_37/python/miniconda3-4.5.12/envs/lsst-scipipe-1172c30/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Call to deprecated function (or staticmethod) Point2D. (Replaced by lsst.geom.Point2D (will be removed before the release of v20.0))
  after removing the cwd from sys.path.


In [19]:
print(centerCoord.getLongitude(), centerCoord.getLatitude())


5.94811 rad -0.163415 rad


In [7]:
def flToMag(flux):
    return -2.5 * np.log10(flux/3631.)

def flToMagErr (flux, fluxErr):
    return np.abs(fluxErr / (-0.4 * flux *np.log(10)))

In [8]:
flToMagErr(refCat[flux], refCat[flux + 'Sigma'])

<Column name='r_fluxSigma' dtype='float64' description=u'' length=53987>
 0.0206571987814
0.00956059634505
  0.148223795127
  0.240897135938
 0.0141438778288
 0.0340419833327
0.00184862105133
  0.167518658488
 0.0681929830223
  0.206876928122
  0.127779938592
 0.0199342422131
             ...
  0.287775452066
  0.313468984679
  0.497595601397
  0.180742329063
   1.56912451733
  0.188275720808
  0.167550404005
  0.272656968577
  0.234597367445
  0.188610847434
 0.0974091052926
  0.148740363339

In [9]:
flToMag(refCat[flux])

<Column name='r_flux' dtype='float64' description=u'' length=53987>
20.3080033934
19.0196287649
22.1845221555
23.4883571125
20.1379299297
22.8453802884
15.1503193122
 22.394483097
21.5339278989
22.6307702146
22.1076345799
18.7081146189
          ...
23.9569734878
23.5566854383
24.2641091708
22.8365874493
25.5527138844
23.3516407016
23.4789347278
22.4897121889
22.6598596365
23.0409478506
 22.834696747
22.9560781548

In [ ]:
font = {'family' : 'serif',
        'color'  : 'darkred',
        'weight' : 'bold',
        'size'   : 25,
        }

plt.rcParams['axes.linewidth'] = 1.5 #set the value globally

f1 = (refCat['r_flux'] > 0) & (refCat['r_fluxSigma'] > 0.) & (refCat['r_flux']/refCat['r_fluxSigma'] > 1.)

fig, (ax0, ax1) = plt.subplots(ncols=2, figsize=(18, 8))
ax0.hist(flToMag(refCat['r_flux'][f1]), bins=80)
ax1.hist(flToMagErr(refCat['r_flux'][f1], refCat['r_fluxSigma'][f1]), bins=80)

fig, (ax2) = plt.subplots(ncols=1, figsize=(18, 8))
ax2.scatter(flToMag(refCat['r_flux'][f1]), flToMagErr(refCat['r_flux'][f1], refCat['r_fluxSigma'][f1]), s=0.2)
ax2.set_xlabel('Magnitude', fontsize=15)
ax2.set_ylabel('$\sigma$(Mag)', fontsize=15)
ax2.tick_params(labelsize=20)

In [ ]:
refCat

In [ ]:
f2 = (refCat['r_flux'] > 0) & (refCat['r_fluxSigma'] > 0.) & (refCat['r_flux']/refCat['r_fluxSigma'] > 5.) 
f2 &= (flToMag(refCat['r_flux']) < 22.5)
fig, (ax0) = plt.subplots(ncols=1, figsize=(10, 10))
ax0.scatter(refCat['coord_ra'], refCat['coord_dec'], s=0.1)
ax0.set_xlabel('RA', fontsize=20)
ax0.set_ylabel('DEC', fontsize=20)
ax0.tick_params(labelsize=20)
fig, (ax1) = plt.subplots(ncols=1, figsize=(10, 10))
ax1.scatter(refCat['coord_ra'][f1], refCat['coord_dec'][f1], s=0.1)
ax1.set_xlabel('RA', fontsize=20)
ax1.set_ylabel('DEC', fontsize=20)
ax1.tick_params(labelsize=20)

In [ ]:
f3 = (refCat['r_flux'] > 0) & (refCat['r_fluxSigma'] > 0.) & (refCat['r_flux']/refCat['r_fluxSigma'] > 0.) 
f3 &= (flToMag(refCat['r_flux']) > 23.2)
fig, (ax0) = plt.subplots(ncols=1, figsize=(10, 10))
ax0.scatter(refCat['coord_ra'][f3], refCat['coord_dec'][f3], s=0.1)
ax0.set_xlabel('RA', fontsize=15)
ax0.set_ylabel('DEC', fontsize=15)
ax0.tick_params(labelsize=15)

In [ ]:
f4 = (f1) & (refCat['coord_ra_err'] > 0.)
fig, (ax0) = plt.subplots(ncols=1, figsize=(10, 10))
ax0.hist(refCat['coord_ra_err'][f4], bins=80)

In [ ]:
        applyColorTerms = self.config.applyColorTerms
        applyCTReason = "config.applyColorTerms is %s" % (self.config.applyColorTerms,)
        if self.config.applyColorTerms is None:
            # apply color terms if color term data is available and photoCatName specified
            ctDataAvail = len(self.config.colorterms.data) > 0
            photoCatSpecified = self.config.photoCatName is not None
            applyCTReason += " and data %s available" % ("is" if ctDataAvail else "is not")
            applyCTReason += " and photoRefCat %s None" % ("is not" if photoCatSpecified else "is")
            applyColorTerms = ctDataAvail and photoCatSpecified

        if applyColorTerms:
            self.log.info("Applying color terms for filterName=%r, config.photoCatName=%s because %s",
                          filterName, self.config.photoCatName, applyCTReason)
            ct = self.config.colorterms.getColorterm(
                filterName=filterName, photoCatName=self.config.photoCatName, doRaise=True)
        else:
            self.log.info("Not applying color terms because %s", applyCTReason)
            ct = None

        if ct:                          # we have a color term to worry about
            fluxFieldList = [getRefFluxField(refSchema, filt) for filt in (ct.primary, ct.secondary)]
            missingFluxFieldList = []
            for fluxField in fluxFieldList:
                try:
                    refSchema.find(fluxField).key
                except KeyError:
                    missingFluxFieldList.append(fluxField)

            if missingFluxFieldList:
                self.log.warn("Source catalog does not have fluxes for %s; ignoring color terms",
                              " ".join(missingFluxFieldList))
                ct = None

        if not ct:
            fluxFieldList = [getRefFluxField(refSchema, filterName)]

        refFluxArrList = []  # list of ref arrays, one per flux field
        refFluxErrArrList = []  # list of ref flux arrays, one per flux field
        for fluxField in fluxFieldList:
            fluxKey = refSchema.find(fluxField).key
            refFluxArr = np.array([m.first.get(fluxKey) for m in matches])
            try:
                fluxErrKey = refSchema.find(fluxField + "Sigma").key
                refFluxErrArr = np.array([m.first.get(fluxErrKey) for m in matches])
            except KeyError:
                # Reference catalogue may not have flux uncertainties; HACK
                self.log.warn("Reference catalog does not have flux uncertainties for %s; using sqrt(flux).",
                              fluxField)
                refFluxErrArr = np.sqrt(refFluxArr)

            refFluxArrList.append(refFluxArr)
            refFluxErrArrList.append(refFluxErrArr)

        if ct:                          # we have a color term to worry about
            refMagArr1 = np.array([abMagFromFlux(rf1) for rf1 in refFluxArrList[0]])  # primary
            refMagArr2 = np.array([abMagFromFlux(rf2) for rf2 in refFluxArrList[1]])  # secondary

            refMagArr = ct.transformMags(refMagArr1, refMagArr2)
            refFluxErrArr = ct.propagateFluxErrors(refFluxErrArrList[0], refFluxErrArrList[1])
        else:
            refMagArr = np.array([abMagFromFlux(rf) for rf in refFluxArrList[0]])

        srcMagArr = np.array([abMagFromFlux(sf) for sf in srcFluxArr])

        # Fitting with error bars in both axes is hard
        # for now ignore reference flux error, but ticket DM-2308 is a request for a better solution
        magErrArr = np.array([abMagErrFromFluxErr(fe, sf) for fe, sf in zip(srcFluxErrArr, srcFluxArr)])
        if self.config.magErrFloor != 0.0:
            magErrArr = (magErrArr**2 + self.config.magErrFloor**2)**0.5

        srcMagErrArr = np.array([abMagErrFromFluxErr(sfe, sf) for sfe, sf in zip(srcFluxErrArr, srcFluxArr)])
        refMagErrArr = np.array([abMagErrFromFluxErr(rfe, rf) for rfe, rf in zip(refFluxErrArr, refFluxArr)])

        return pipeBase.Struct(
            srcMag=srcMagArr,
            refMag=refMagArr,
            magErr=magErrArr,
            srcMagErr=srcMagErrArr,
            refMagErr=refMagErrArr,
            refFluxFieldList=fluxFieldList,
        )

In [3]:
from lsst.pipe.tasks.colorterms import ColortermLibrary
from lsst.afw.image import abMagFromFlux, abMagErrFromFluxErr, fluxFromABMag, Calib

In [4]:
import os
from lsst.utils import getPackageDir

hscConfigDir = os.path.join(getPackageDir("obs_subaru"), "config", "hsc")
colorterms = ColortermLibrary()
colorterms.load(os.path.join(hscConfigDir, 'colorterms.py'))

photoCatName = 'ps1*'

ct = colorterms.getColorterm(
            filterName='g', photoCatName=photoCatName, doRaise=True)

In [5]:
ct.

lsst.pipe.tasks.colorterms.Colorterm(primary='g', secondary='r', c0=0.00730066, c1=0.06508481, c2=-0.0151057)

In [6]:
ct.secondary

'r'

In [20]:
mag = abMagFromFlux(refCat[2001]['g_flux'])
err = abMagErrFromFluxErr(refCat[2001]['g_flux'], refCat[2001]['g_fluxSigma'])
err2 = abMag

mag, err

(23.84107582255976, 5.108196971524156)

In [16]:
abMagErrFromFluxErr

<function lsst.afw.image.calib.PyCapsule.abMagErrFromFluxErr>

In [27]:
a = np.arange(10)
b = np.arange(10)*2
a, b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]))

In [25]:
c =[i*j for i,j in zip(a,b)]

In [26]:
c

[0, 2, 8, 18, 32, 50, 72, 98, 128, 162]

In [30]:
filters = ['r', 'i']
for f in filters :
    print(f)

r
i


In [31]:
test = {}
test['g'] = a
test['r'] = b
test

{'g': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'r': array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])}